//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersManager
    {
        public int UsersManager_ID { get; set; }
        public string UsersManager_Name { get; set; }
        public string UsersManager_Pass { get; set; }
    }
}
